apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-search 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-search
  template:
    metadata:
      labels:
        app: product-search
    spec:
      containers:
      - name: product-search
        image: demoacr1480.azurecr.io/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Product Search placeholder"